### PR TITLE
Check Code

### PR DESCRIPTION
**Pull request by jobysanthosh**

### CODE REVIEW

**Comment by janfernandosmoothstack** [comment]
For your DAO Librarian, there should be no main function.

Librarian Menu:
- Clean up your code
      - The indentation is not consistent. It needs to be uniform to make your code more readable
      - Your style of coding is changing throughout your code. You need to pick a style and stick to it.
        For example in places you write code like this:
        public {
              -your code
        }
  
        While in other places it looks like this:
        public
        {
               -your code
        }
        
- In your update method you have a check that you do repeatedly to check if the user entered N/A or quit. Since you are doing it so often I would create a method in your interface that you can call to carry our this comparison and just pass in the value to it instead of repeating the same if statement.

**Comment by sayanastha39** [comment]
Hello Joby,

Will you be changing your datatype for bookId back to int? I see you have it as string on Book.java The SQL datatype for bookId is int type.

**Comment by sayanastha39** [comment]
I have also noticed that your DAO has all your service layer, DAO, and presentation in one class. It would be nice if you separated it into different packages depending on its functionality.

**Comment by jobysanthosh** [comment]
Indentation is fixed and data types have been set to the requirements. Will try to hurry up and finish the update method

**Pull request closed without merging**
